version: 0.2
--- 
phases: 
  install: 
    docker: 18
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "Invoke-Expression -Command (Get-ECRLoginCommand -Region us-east-1).Command"
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t webappmvc ."
      - "docker tag webappmvc:latest 543816070942.dkr.ecr.us-east-1.amazonaws.com/webappmvc:v1.1.2"
  post_build: 
    commands: 
      - "docker push 543816070942.dkr.ecr.us-east-1.amazonaws.com/webappmvc:latest"
