
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t webappmvc ."
      - "docker tag webappmvc:latest 543816070942.dkr.ecr.us-east-1.amazonaws.com/webappmvc:v1"
  install: 
    runtime-versions: 
      docker: 18
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 543816070942.dkr.ecr.us-east-1.amazonaws.com/webappmvc:v1"
  pre_build: 
    commands: 
      - "echo Logging in to Amazon ECR..."
      - "Invoke-Expression -Command (Get-ECRLoginCommand -Region us-east-1).Command"
